/*
 * This file is generated by jOOQ.
 */
package ru.hse.spb.keylogger.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.hse.spb.keylogger.db.tables.Worklog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorklogRecord extends UpdatableRecordImpl<WorklogRecord> implements Record8<Long, String, String, String, Long, String, String, Long> {

    private static final long serialVersionUID = -909067056;

    /**
     * Setter for <code>public.worklog.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.worklog.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.worklog.changes</code>.
     */
    public void setChanges(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.worklog.changes</code>.
     */
    public String getChanges() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.worklog.file_name</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.worklog.file_name</code>.
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.worklog.project_name</code>.
     */
    public void setProjectName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.worklog.project_name</code>.
     */
    public String getProjectName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.worklog.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.worklog.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.worklog.action</code>.
     */
    public void setAction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.worklog.action</code>.
     */
    public String getAction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.worklog.params</code>.
     */
    public void setParams(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.worklog.params</code>.
     */
    public String getParams() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.worklog.worker_id</code>.
     */
    public void setWorkerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.worklog.worker_id</code>.
     */
    public Long getWorkerId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, Long, String, String, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, Long, String, String, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Worklog.WORKLOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Worklog.WORKLOG.CHANGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Worklog.WORKLOG.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Worklog.WORKLOG.PROJECT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Worklog.WORKLOG.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Worklog.WORKLOG.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Worklog.WORKLOG.PARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Worklog.WORKLOG.WORKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getChanges();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getWorkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getChanges();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getWorkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value2(String value) {
        setChanges(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value3(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value4(String value) {
        setProjectName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value5(Long value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value6(String value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value7(String value) {
        setParams(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value8(Long value) {
        setWorkerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, String value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorklogRecord
     */
    public WorklogRecord() {
        super(Worklog.WORKLOG);
    }

    /**
     * Create a detached, initialised WorklogRecord
     */
    public WorklogRecord(Long id, String changes, String fileName, String projectName, Long timestamp, String action, String params, Long workerId) {
        super(Worklog.WORKLOG);

        set(0, id);
        set(1, changes);
        set(2, fileName);
        set(3, projectName);
        set(4, timestamp);
        set(5, action);
        set(6, params);
        set(7, workerId);
    }
}
