/*
 * This file is generated by jOOQ.
 */
package ru.hse.spb.keylogger.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.hse.spb.keylogger.db.tables.SchemaVersion;
import ru.hse.spb.keylogger.db.tables.Worker;
import ru.hse.spb.keylogger.db.tables.Worklog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1643082749;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = ru.hse.spb.keylogger.db.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.worker</code>.
     */
    public final Worker WORKER = ru.hse.spb.keylogger.db.tables.Worker.WORKER;

    /**
     * The table <code>public.worklog</code>.
     */
    public final Worklog WORKLOG = ru.hse.spb.keylogger.db.tables.Worklog.WORKLOG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.WORKER_ID_SEQ,
            Sequences.WORKLOG_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SchemaVersion.SCHEMA_VERSION,
            Worker.WORKER,
            Worklog.WORKLOG);
    }
}
