/*
 * This file is generated by jOOQ.
 */
package ru.hse.spb.keylogger.db;


import javax.annotation.Generated;

import ru.hse.spb.keylogger.db.tables.SchemaVersion;
import ru.hse.spb.keylogger.db.tables.Worker;
import ru.hse.spb.keylogger.db.tables.Worklog;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = ru.hse.spb.keylogger.db.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.worker</code>.
     */
    public static final Worker WORKER = ru.hse.spb.keylogger.db.tables.Worker.WORKER;

    /**
     * The table <code>public.worklog</code>.
     */
    public static final Worklog WORKLOG = ru.hse.spb.keylogger.db.tables.Worklog.WORKLOG;
}
