/*
 * This file is generated by jOOQ.
 */
package ru.hse.spb.keylogger.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Worker implements Serializable {

    private static final long serialVersionUID = 606775798;

    private Long   id;
    private String login;
    private String password;
    private String token;

    public Worker() {}

    public Worker(Worker value) {
        this.id = value.id;
        this.login = value.login;
        this.password = value.password;
        this.token = value.token;
    }

    public Worker(
        Long   id,
        String login,
        String password,
        String token
    ) {
        this.id = id;
        this.login = login;
        this.password = password;
        this.token = token;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Worker (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(password);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
