/*
 * This file is generated by jOOQ.
 */
package ru.hse.spb.keylogger.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.hse.spb.keylogger.db.Indexes;
import ru.hse.spb.keylogger.db.Keys;
import ru.hse.spb.keylogger.db.Public;
import ru.hse.spb.keylogger.db.tables.records.WorkerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Worker extends TableImpl<WorkerRecord> {

    private static final long serialVersionUID = -1940639602;

    /**
     * The reference instance of <code>public.worker</code>
     */
    public static final Worker WORKER = new Worker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkerRecord> getRecordType() {
        return WorkerRecord.class;
    }

    /**
     * The column <code>public.worker.id</code>.
     */
    public final TableField<WorkerRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('worker_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.worker.login</code>.
     */
    public final TableField<WorkerRecord, String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * The column <code>public.worker.password</code>.
     */
    public final TableField<WorkerRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * The column <code>public.worker.token</code>.
     */
    public final TableField<WorkerRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * Create a <code>public.worker</code> table reference
     */
    public Worker() {
        this(DSL.name("worker"), null);
    }

    /**
     * Create an aliased <code>public.worker</code> table reference
     */
    public Worker(String alias) {
        this(DSL.name(alias), WORKER);
    }

    /**
     * Create an aliased <code>public.worker</code> table reference
     */
    public Worker(Name alias) {
        this(alias, WORKER);
    }

    private Worker(Name alias, Table<WorkerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Worker(Name alias, Table<WorkerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Worker(Table<O> child, ForeignKey<O, WorkerRecord> key) {
        super(child, key, WORKER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_WORKER__LOGIN, Indexes.IDX_WORKER__TOKEN, Indexes.WORKER_LOGIN_KEY, Indexes.WORKER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WorkerRecord, Long> getIdentity() {
        return Keys.IDENTITY_WORKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WorkerRecord> getPrimaryKey() {
        return Keys.WORKER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WorkerRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkerRecord>>asList(Keys.WORKER_PKEY, Keys.WORKER_LOGIN_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Worker as(String alias) {
        return new Worker(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Worker as(Name alias) {
        return new Worker(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Worker rename(String name) {
        return new Worker(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Worker rename(Name name) {
        return new Worker(name, null);
    }
}
